name = "Sad"
uuid = "86303e7b-04d2-42a2-bc71-7ba20542e124"
authors = ["Kostas Andreadis"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
NCDatasets = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
